services:
  - type: web
    name: phytoscan-ai
    env: python
    region: frankfurt
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn phytoscan.wsgi:application --bind 0.0.0.0:$PORT --workers 1 --timeout 300"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: phytoscan.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: GROQ_API_KEY
        sync: false               # À saisir manuellement dans le dashboard Render
      - key: DATABASE_URL
        fromDatabase:
          name: phytoscan-db
          property: connectionString

databases:
  - name: phytoscan-db
    databaseName: phytoscan
    user: phytoscan
    plan: free
